# Generated by Django 4.2.2 on 2024-02-26 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_dishe_d"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishe",
            name="d",
        ),
    ]
