# Generated by Django 4.2.2 on 2024-02-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_dishe_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='distance_from_stadium',
        ),
    ]
