# Generated by Django 5.0.2 on 2024-02-27 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_dishe_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
