# Generated by Django 5.0.2 on 2024-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=20),
        ),
    ]
