# Generated by Django 4.2.2 on 2024-02-26 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_description_hotel_properties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('population', models.BigIntegerField()),
                ('creation_date', models.IntegerField()),
                ('transport', models.TextField()),
                ('stad_id', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.stadiums')),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('distance_from_stadium', models.FloatField()),
                ('image', models.CharField(max_length=300)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cities')),
            ],
        ),
        migrations.CreateModel(
            name='dishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cities')),
            ],
        ),
    ]
