# Generated by Django 4.2.2 on 2024-02-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cities_place_dishe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='image',
            field=models.CharField(default='hh', max_length=350),
            preserve_default=False,
        ),
    ]
